#!/usr/bin/env bash

for src in $(find -H $(pwd -P) -name '*.dotfile')
do
  dst="$HOME/.$(basename "${src%.*}")"
  echo "❌  Deleting $dst"
  rm -rf "$dst"
  echo "🔄  Symlinking $src ➡️  $dst..."
  ln -s "$src" "$dst"
done

echo "Symlink complete ✅"
